### ISSUE TITLE
Microsoft Kinect 2 SDK vs. libfreenect2

### ISSUE THREAD

**Issue by Daniel-Valentine** [ExerciseCheck/exercisecheck#1]
Project currently uses the propriety SDK, but should we consider using the OpenKinect library for interfacing with the Kinect?

https://github.com/OpenKinect/libfreenect2

In addition, the DepthJS browser extension/plugin can interface between the Kinect and libfreenect (per the libfreenect [docs](https://openkinect.org/wiki/Javascript_Wrapper)):

https://github.com/doug/depthjs

**Comment by saurabh21289** [comment]
When we started the project couple years ago, libfreenect2 was far from mature and didn't support IR and depth image processing at that time. From the latest documentation it looks like that it now does support those features. I'm still concerned about this one issue they've listed which is yet to be resolved: 

"Unstable USB and crashes. Due to differences in driver support, USB problems can happen a lot. Error handling in libfreenect2 is not fully verified for production use."

The depthjs extension might not work with the latest version of chrome since it hasn't been maintained since 2013, we'll have to try. 

We should perhaps give libfreenect2 a go and see what the performance and stability is like. Here are some [pros and cons](https://stackoverflow.com/questions/7706448/official-kinect-sdk-vs-open-source-alternatives) we considered before settling with the Microsoft SDK.

**Comment by Daniel-Valentine** [comment]
What are the OSes ExerciseCheck is supposed to be deployed on? If it's Windows 8+, then it shouldn't be an issue – we can just build the Kinect2 module for use in an Electron app, since we don't need cross platform support. We would need libfreenect2 if whoever is planning to use ExerciseCheck isn't on Windows.

Of course, if we're trying to move away from the Kinect2 node module (which is my understanding) then the issue is moot since ExerciseCheck would need adjustment to make API calls to whichever SDK we use.

**Comment by saurabh21289** [comment]
At the moment ExcerciseCheck(EC) can be deployed on Windows 7 onwards for the server-side (that is the system which is physically connected to the Kinect). Server-side must have a USB 3.0 port for the Kinect. 
In the current design the Kinect2 node module allows any client on the network to access the UI to see the subject exercising in real-time via a web-browser, will this feature be available when deployed via Electron?

Kinect2 node can be deployed via electron also as shown here: https://github.com/wouterverweirder/kinect2/tree/master/examples/skeleton-bones-electron
But I have never tested that.
If we move away from Kinect2 module, then how are we planning to interface the electron application with the Kinect hardware?

**Comment by mingxin-zheng** [comment]
My understanding is that if we use the Kinect 2 module on the electron app, then the laptop (connecting to Kinect) has to be the server. 

If so, it is not preferable because keeping the server on patient's laptop isn't a secure/robust solution.
If not, since cross platform isn't the primary focus of project,  we can have the patient/PT install the software through the Electron, but all the data will be streamed to a remote server.

**Comment by saurabh21289** [comment]
Ok, let me see if I understand correctly. Are we looking to have a design like this?
![kinect design](https://user-images.githubusercontent.com/13815692/31785362-f4b91a44-b4d2-11e7-885e-803fc755ba45.jpg)
Will we have any processing on the patient's device? If not, that is ok. My concern is that the Kinect generates a lot of data in a matter of milliseconds. Can we deploy an instance of the Electron application on the patient's laptop which stores the data & compresses it to be sent over the network? The ExerciseCheck app with the UI elements for evaluation will be on the server.

**Comment by Daniel-Valentine** [comment]
Unfortunately the client computer will need some way to interface with the Kinect even if it's just passing data along to a server for processing, especially since it's a foreign hardware device for which most OSes don't have inbuilt support as far as I know.

Re network concerns: some compression may be necessary but we can diminish latency problems by using UDP, and I think we could use [Node's dgram library](https://nodejs.org/api/dgram.html) to implement the protocol.
